# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("QWidget{\n"
"    color:#232C51;\n"
"    background:white;\n"
"    border-top:1px solid darkGray;\n"
"    border-bottom:1px solid darkGray;\n"
"    border-right:1px solid darkGray;\n"
"    border-top-right-radius:10px;\n"
"    border-bottom-right-radius:10px;\n"
"  }\n"
"  QLabel{\n"
"    border:none;\n"
"    font-size:16px;\n"
"    font-weight:700;\n"
"    font-family: \"Helvetica Neue\", Helvetica, Arial, sans-serif;\n"
"  }")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(70, 230, 75, 23))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    color:black;\n"
"    font-family:微软雅黑;\n"
"    border: 2px solid DarkGray;\n"
"    background:rgb(255, 255, 255, 60);\n"
"}\n"
"QPushButton:hover{\n"
"    border: 1px solid Gray;\n"
"    background:rgb(255, 255, 255, 90);\n"
"}\n"
"QPushButton:pressed{\n"
"    border: 2px solid DarkGray;\n"
"    background:rgb(255, 255, 255, 30);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 260, 111, 51))
        self.label.setStyleSheet("border-image:url(C:/Users/DELL/Pictures/Saved Pictures/1.jpg);")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.menufil = QtWidgets.QMenu(self.menubar)
        self.menufil.setObjectName("menufil")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionopen = QtWidgets.QAction(MainWindow)
        self.actionopen.setObjectName("actionopen")
        self.menufil.addAction(self.actionopen)
        self.menubar.addAction(self.menufil.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.menufil.setTitle(_translate("MainWindow", "fil"))
        self.actionopen.setText(_translate("MainWindow", "open"))
