# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Java\Java program\pyprogram\accountbook\UI\Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(263, 244)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 90, 241, 70))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setSpacing(6)
        self.formLayout.setObjectName("formLayout")
        self.LineEdit_account = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.LineEdit_account.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.LineEdit_account.setFont(font)
        self.LineEdit_account.setInputMethodHints(QtCore.Qt.ImhNone)
        self.LineEdit_account.setMaxLength(32)
        self.LineEdit_account.setObjectName("LineEdit_account")
        self.LineEdit_account.setStyleSheet("{\n"
        "background:#FF6694;\n"
        "border-radius:10px;\n"
        "}\n"
        "QPushButton:hover\n"
        "{\n"
        "background:#FF0000;\n"
        "}\n"
        "\n"
        "")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.LineEdit_account)
        self.Label_password = QtWidgets.QLabel(self.formLayoutWidget)
        self.Label_password.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.Label_password.setFont(font)
        self.Label_password.setObjectName("Label_password")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Label_password)
        self.LineEdit_password = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.LineEdit_password.setFont(font)
        self.LineEdit_password.setMaxLength(32)
        self.LineEdit_password.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.LineEdit_password.setObjectName("LineEdit_password")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.LineEdit_password)
        self.Label_account = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.Label_account.setFont(font)
        self.Label_account.setObjectName("Label_account")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label_account)
        self.label_LoginTips = QtWidgets.QLabel(self.centralwidget)
        self.label_LoginTips.setGeometry(QtCore.QRect(90, 20, 144, 35))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_LoginTips.setFont(font)
        self.label_LoginTips.setObjectName("label_LoginTips")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 190, 241, 37))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_launch = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_launch.setFont(font)
        self.pushButton_launch.setObjectName("pushButton_launch")
        self.pushButton_launch.setStyleSheet("QPushButton{\n"
                      "    border:0px;\n"
                      "    height:30px;\n"
                      "    border-radius:15px;\n"
                      "    font-family:\'Microsoft YaHei\';\n"
                      "    font-size:20px;\n"
                      "    color:white;\n"
                      "    background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #fbc2eb, stop:1 #a6c1ee);\n"
                      "    }\n"
                      "\n"
                      " QPushButton:hover{\n"
                      "     background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #ffd2f0, stop:1 #b0cbf8);\n"
                      " }\n"
                      " \n"
                      " QPushButton:pressed{\n"
                      "     background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #e1aad2, stop:1 #92adda);\n"
                      "     }")
        self.horizontalLayout.addWidget(self.pushButton_launch)
        self.pushButton_exit = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_exit.setFont(font)
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.pushButton_exit.setStyleSheet("QPushButton{\n"
"    color:black;\n"
"    font-family:微软雅黑;\n"
"    border: 2px solid DarkGray;\n"
"    background:rgb(255, 255, 255, 60);\n"
"}\n"
"QPushButton:hover{\n"
"    border: 1px solid Gray;\n"
"    background:rgb(255, 255, 255, 90);\n"
"}\n"
"QPushButton:pressed{\n"
"    border: 2px solid DarkGray;\n"
"    background:rgb(255, 255, 255, 30);\n"
"}")
        self.horizontalLayout.addWidget(self.pushButton_exit)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 51, 51))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/logo/logo1.jpg"))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pushButton_exit.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.LineEdit_password, self.LineEdit_account)
        MainWindow.setTabOrder(self.LineEdit_account, self.pushButton_launch)
        MainWindow.setTabOrder(self.pushButton_launch, self.pushButton_exit)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "记账软件"))
        self.LineEdit_account.setText(_translate("MainWindow", "admin"))
        self.LineEdit_account.setPlaceholderText(_translate("MainWindow", "admin"))
        self.Label_password.setText(_translate("MainWindow", "密码："))
        self.LineEdit_password.setPlaceholderText(_translate("MainWindow", "初始密码123"))
        self.Label_account.setText(_translate("MainWindow", "账号："))
        self.label_LoginTips.setText(_translate("MainWindow", "登陆软件"))
        self.pushButton_launch.setText(_translate("MainWindow", "登陆"))
        self.pushButton_exit.setText(_translate("MainWindow", "退出软件"))
import ico.ico_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
